project:
  type: website
  output-dir: docs

website:
  site-url: "https://www.muratkoptur.com/MyDsProjects"
  title: "Murat Koptur Data Science Blog & Projects"
  description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  navbar:
    right:
      - href: "/"
        icon: "house-fill"
      - href: "/about.html"
        icon: "person-fill"
      - href: "https://twitter.com/mrtkp9993"
        icon: "twitter"
      - href: "https://www.instagram.com/mrtkp9993/"
        icon: "instagram"
      - href: "https://www.linkedin.com/in/muratkoptur/"
        icon: "linkedin"
      - href: "https://github.com/mrtkp9993"
        icon: "github"
      - href: "mailto:muratkoptur@yandex.com"
        icon: "mailbox"
  open-graph:
    title: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  twitter-card:
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    creator: "@mrtkp9993"
    site: "@mrtkp9993"
  google-analytics: "G-TQSZS8HRH9"
  cookie-consent: true
  page-footer:
    left: |
          Thanks for reading. If you enjoyed, please share it.\
          Support my work from [GitHub Sponsors](https://github.com/sponsors/mrtkp9993/) and [Patreon](https://patreon.com/muratkoptur?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator).
    right:
      - href: "https://twitter.com/mrtkp9993"
        icon: "twitter"
      - href: "https://www.instagram.com/mrtkp9993/"
        icon: "instagram"
      - href: "https://www.linkedin.com/in/muratkoptur/"
        icon: "linkedin"
      - href: "https://github.com/mrtkp9993"
        icon: "github"
      - href: "mailto:muratkoptur@yandex.com"
        icon: "mailbox"

resources:
  - "ogimg.png"
  - "profile.png"

theme:
  light:
    - yeti
    - custom.scss

comments:
  hypothesis:
    theme: clean
    openSidebar: false

format:
  html:
    code-copy: true
    code-line-numbers: true
    fig-align: center
    citation: true
    page-layout: article
    include-in-header: header.html
    include-after-body: footer.html
