project:
  type: website
  output-dir: docs

website:
  title: "My Data Science Blog & Projects"
  description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  navbar:
    right:
      - href: "about.qmd"
        text: About Me
  reader-mode: true
  open-graph:
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  twitter-card:
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    creator: "@mrtkp9993"
    site: "@mrtkp9993"
  google-analytics: "G-TQSZS8HRH9"
  cookie-consent: true
  body-footer: |
    ---\
    Thanks for reading. If you enjoyed, please share it.\
    Support my work from here [GitHub Sponsors](https://github.com/sponsors/mrtkp9993/).\
    You can support me also on [Patreon](https://patreon.com/muratkoptur?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator).

resources:
  - "ogimg.png"
  - "profile.png"

theme:
  light: simplex
  dark: darkly

comments:
  utterances:
    repo: mrtkp9993/MyDsProjects

format:
  html:
    include-in-header: header.html
    include-after-body: footer.html
