project:
  type: website
  output-dir: docs

website:
  title: "My Data Science Blog & Projects"
  description: "Murat Koptur - Data Scientst - Data Science Blog & Projects"
  navbar:
    right:
      - href: https://www.linkedin.com/in/muratkoptur/
        text: LinkedIn
      - href: https://github.com/mrtkp9993
        text: GitHub
      - href: https://muratkoptur.com
        text: Personal Website
  reader-mode: true
  open-graph:
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    description: "Murat Koptur - Data Scientst - Data Science Blog & Projects"
  twitter-card:
    description: "Murat Koptur - Data Scientst - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    creator: "@mrtkp9993"
    site: "@mrtkp9993"
  google-analytics: "G-TQSZS8HRH9"
  cookie-consent: true
  body-footer: |
    ---\
    Thanks for reading. If you enjoyed, please share it.\
    Support my work from here [GitHub Sponsors](https://github.com/sponsors/mrtkp9993/).

theme:
  light: simplex
  dark: darkly

comments:
  utterances:
    repo: mrtkp9993/MyDsProjects

format:
  html:
    include-in-header: header.html
    include-after-body: footer.html
