project:
  type: website
  output-dir: docs

website:
  site-url: "https://www.muratkoptur.com/MyDsProjects"
  title: "My Data Science Blog & Projects"
  description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  navbar:
    right:
      - href: "about.qmd"
        text: About Me
  open-graph:
    title: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
  twitter-card:
    description: "Murat Koptur - Data Scientist - Data Science Blog & Projects"
    image: "https://muratkoptur.com/MyDsProjects/ogimg.png"
    creator: "@mrtkp9993"
    site: "@mrtkp9993"
  google-analytics: "G-TQSZS8HRH9"
  cookie-consent: true
  page-footer:
    left: |
          Thanks for reading. If you enjoyed, please share it.\
          Support my work from [GitHub Sponsors](https://github.com/sponsors/mrtkp9993/) and [Patreon](https://patreon.com/muratkoptur?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=creatorshare_creator).
    center:
      '<a href="//www.dmca.com/Protection/Status.aspx?ID=b742ca88-8c4f-4803-82cb-d32b9b87901e" title="DMCA.com Protection Status" class="dmca-badge"> <img src ="https://images.dmca.com/Badges/dmca_protected_sml_120l.png?ID=b742ca88-8c4f-4803-82cb-d32b9b87901e"  alt="DMCA.com Protection Status" /></a>  <script src="https://images.dmca.com/Badges/DMCABadgeHelper.min.js"> </script>'
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/muratkoptur/
      - icon: github
        href: https://github.com/mrtkp9993
      - icon: instagram
        href: https://www.instagram.com/mrtkp9993/

resources:
  - "ogimg.png"
  - "profile.png"

theme:
  light: yeti
  dark: solar

comments:
  hypothesis:
    theme: clean
    openSidebar: false

format:
  html:
    page-layout: article
    include-in-header: header.html
